### ISSUE TITLE
The prime 'd6c094ad 57f5374f 68d58c7b 096872d9....' is not a safe prime

### ISSUE THREAD

**Issue by rdegraaf** [eSentire/nmap-esentire#3]
Your script documents the prime beginning in "d6c094ad 57f5374f 68d58c7b 096872d9" as "weakdh.org/1024-bit MODP group with safe prime modulus", but it is not a safe prime.  To demonstrate this, run the following Python script:

```
import gmpy
p = gmpy.mpz('\
  d6c094ad 57f5374f 68d58c7b 096872d9 45cee1f8 2664e059 4421e1d5 e3c8e98b \
  c3f0a6af 8f92f19e 3fef9337 b99b9c93 a055d55a 96e42573 4005a68e d47040fd \
  f00a5593 6eba4b93 f64cba1a 004e4513 611c9b21 7438a703 a2060c20 38d0cfaa \
  ffbba48f b9dac4b2 450dc58c b0320a03 17e2a31b 44a02787 c657fb0c 0cbec11d', 16)
q = (p-1)/2
gmpy.is_prime(p)
gmpy.is_prime(q)
```

I have no idea what generator is used with that prime or what its order is.

**Comment by jgajek** [comment]
Good catch, thank you!  I thought I tested them all, but looks like I missed that one.  I will retest them all and fix the descriptions as necessary.
